# Generated by Django 3.2.9 on 2021-12-08 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='likes',
            new_name='like',
        ),
    ]
