# Generated by Django 3.2.9 on 2021-12-20 07:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderroom',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='цена'),
        ),
        migrations.AlterField(
            model_name='orderroom',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_room', to='hotel.room', verbose_name='комнаты'),
        ),
        migrations.AlterField(
            model_name='orderroom',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_user', to=settings.AUTH_USER_MODEL, verbose_name='клиент'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.PositiveSmallIntegerField(choices=[(1, 'однокомнатная'), (2, 'двухкомнатная'), (3, 'трехкомнатная')], db_index=True, verbose_name='колличество комнат'),
        ),
    ]
