# Generated by Django 3.2.9 on 2021-12-20 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20211220_1003'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderroom',
            old_name='end_day',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='orderroom',
            old_name='start_day',
            new_name='start_date',
        ),
    ]
